name: hollagrafik
favicon: null
layout_spectrum: 0.8114042575471103
typography_spectrum: 0.8280475896317512
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6662786395754665
  lightness: 0.16649379371665418
  saturation: 0.9736249386332929
  rhythmicContrast: 0.3702908777631819
purpose: []
